trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: pack
  inputs:
    command: 'pack'
    packagesToPack: 'Polferov.SwaggerEnumsAsStrings/*.csproj'
    includesymbols: true
    includesource: true
    versioningScheme: 'off'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'

- task: NuGetCommand@2
  displayName: push
  continueOnError: true
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'
    verbosityPush: 'Normal'